# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developersite', '0003_auto_20160722_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='contact',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='g_plus',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
